/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class mil_darpa_xlang_ThunderdomeNativeAdapter */

#ifndef _Included_mil_darpa_xlang_ThunderdomeNativeAdapter
#define _Included_mil_darpa_xlang_ThunderdomeNativeAdapter
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     mil_darpa_xlang_ThunderdomeNativeAdapter
 * Method:    invoke
 * Signature: (Ljava/lang/String;)Lmil/darpa/xlang/TdValue;
 */
JNIEXPORT jobject JNICALL Java_mil_darpa_xlang_ThunderdomeNativeAdapter_invoke__Ljava_lang_String_2
  (JNIEnv *, jobject, jstring);

/*
 * Class:     mil_darpa_xlang_ThunderdomeNativeAdapter
 * Method:    invoke
 * Signature: (Ljava/lang/String;Lmil/darpa/xlang/TdValue;)Lmil/darpa/xlang/TdValue;
 */
JNIEXPORT jobject JNICALL Java_mil_darpa_xlang_ThunderdomeNativeAdapter_invoke__Ljava_lang_String_2Lmil_darpa_xlang_TdValue_2
  (JNIEnv *, jobject, jstring, jobject);

/*
 * Class:     mil_darpa_xlang_ThunderdomeNativeAdapter
 * Method:    invoke
 * Signature: (Ljava/lang/String;Lmil/darpa/xlang/TdValue;Lmil/darpa/xlang/TdValue;)Lmil/darpa/xlang/TdValue;
 */
JNIEXPORT jobject JNICALL Java_mil_darpa_xlang_ThunderdomeNativeAdapter_invoke__Ljava_lang_String_2Lmil_darpa_xlang_TdValue_2Lmil_darpa_xlang_TdValue_2
  (JNIEnv *, jobject, jstring, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
